### ISSUE TITLE
ArrayList/Front/backend work

### ISSUE THREAD

**Issue by Gabrielboudreau** [Gabrielboudreau/CSATeam#18]
[Frontend](https://github.com/JayManjrekar/WebsiteDesign)

[Backend](https://github.com/Gabrielboudreau/CSATeam)

[Deployed Site](https://jaymanjrekar.github.io/WebsiteDesign)

Array List (Pairs): 

[Rohan/Kinish](https://kinerboi.github.io/myFirstRepopart2/2022/10/06/ListArray.html)

Gabriel/Jay: [ArrayList](https://gabrielboudreau.github.io/CSPAT1/2022/10/07/arrayList.html) and [ArrayList #2](https://jaymanjrekar.github.io/jaysfastpages/2022/10/16/arraylist.html)

**Comment by jm1021** [comment]
Jay discussed a method with add, remove method.   Kinish discussed comparison.  Rohan discussed an enhance for loop.  Jay discussed .equals.   Seems like they covered everything.

Project started showing API and formatting.   They also talked about POJO and  more.   Ahead on the project stuff.  

2.8 for everyone as they all had insights, except Gabe 2.7

**Comment by rjawesome** [comment]
Grading Complete
