### ISSUE TITLE
ArrayList and Team Setup

### ISSUE THREAD

**Issue by Gabrielboudreau** [Gabrielboudreau/CSATeam#19]
ArrayList (Individual): 

Jay:

Gabe: [ArrayList](https://gabrielboudreau.github.io/CSPAT1/2022/10/07/arrayList.html)

Rohan:

Kinish:

Team Repos:

[FrontEnd](https://github.com/Gabrielboudreau/frontTeamCSA)

[BackEnd](https://github.com/Gabrielboudreau/CSATeam)

**Comment by rjawesome** [comment]
Duplicate of other issue
