### ISSUE TITLE
Store count

### ISSUE THREAD

**Issue by rjawesome** [Gabrielboudreau/CSATeam#22]
Currently our frontend website has a field for the count of data but this is not supplied/stored by the backend. We should add this to the POJO so frontend can access.

**Comment by rjawesome** [comment]
Backend Done! This can now be passed onto frontend to complete.

Example JSON object from backend (frontend needs to use ``count`` field):
```json
{"id":4,"name":"kinish","data":"10.0, 15.0, 20.0, 25.0, 30.0, 50.0, 100.0","mean":35.714285714285715,"median":25.0,"standardDeviation":26.24453295839119,"count":7}
```

**Comment by JayManjrekar** [comment]
Count has been finished on the front end

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/89176673/199295496-8aace88c-1d83-4156-97c7-d3147f6fb007.png">
