### ISSUE TITLE
Add Graphs

### ISSUE THREAD

**Issue by Gabrielboudreau** [Gabrielboudreau/CSATeam#26]
Add visuals for the statistical data
- [x] Histogram (Generated)
- [x] Histogram (Used in database)
- [x] Dotplot (Generated)
- [x] Dotplot (Used in database)
- [x] Boxplot (Generated)
- [x] Boxplot (Used in database)
- [x] Stemgraph (Generated)
- [x] Stemgraph (Used in database)

**Comment by rjawesome** [comment]
See https://www.jfree.org/jfreechart/api/javadoc/org/jfree/data/statistics/HistogramDataset.html & https://mvnrepository.com/artifact/jfree/jfreechart/1.0.13

**Comment by rjawesome** [comment]
Generated Histogram in Java. Still need to do some integration with API/exposing the image (in graphs branch)

![image](https://user-images.githubusercontent.com/16053597/198493442-b20768e5-939d-4fdd-95dc-8b2d68e812dc.png)

**Comment by rjawesome** [comment]
Histogram should be done. Model can be followed for other graphs.

**Comment by rjawesome** [comment]
Histogram, Box Plot, Dot Plot Completed on respective Pull Requests. Still need to work on stem plot.

**Comment by rjawesome** [comment]
All graphs completed
