### ISSUE TITLE
Week 5 Group Issue

### ISSUE THREAD

**Issue by Gabrielboudreau** [Gabrielboudreau/CSATeam#3]
Group Tasks (Design)
- [x] WireFrame Issue [Link](https://github.com/Gabrielboudreau/CSATeam/issues/2)
![image](https://user-images.githubusercontent.com/16053597/192435810-70d380f0-9112-4b52-ba9f-d6b6b7f85486.png)

- [x] Design Issue [Link](https://github.com/Gabrielboudreau/CSATeam/issues/1)
![Screenshot (10)](https://user-images.githubusercontent.com/89223461/192182877-5918d28f-3c78-4e1f-b355-1cea00af902f.png)

Individual Tasks
Kinish 2.7
- [x] JavaScript Project [Link](https://kinerboi.github.io/myFirstRepopart2/todo) 
- [x] Fibonacci Sequence [Link](https://kinerboi.github.io/myFirstRepopart2/cb/2022/09/25/Fibonacci.html)

Jay 2.7
- [x] JavaScript Project [Stats Quiz](https://jaymanjrekar.github.io/jaysfastpages/stats/) 
- [x] Fibonacci Sequence [Link](url)

Rohan
- [x] JavaScript Project [Link](https://rohanj.dev/apcsa_fastpages/mean/) 
- [x] Fibonacci Sequence [Link](https://rohanj.dev/apcsa_fastpages/cb/2022/09/22/fib.html)

Gabriel 2.5 Fibo Issues
- [x] JavaScript Project SD calc, [JS](https://gabrielboudreau.github.io/CSPAT1/js)

![Image](https://user-images.githubusercontent.com/89223461/192345035-754f7fec-af11-4dd6-9486-fef935683cd8.png)

- [ ] Fibonacci Sequence [Link](https://gabrielboudreau.github.io/CSPAT1/2022/09/22/fibonacci.html)

**Comment by Gabrielboudreau** [comment]
Rohan's code is good, multiple iterations of Fibo created and defined separately.  Mean Calc has good functionality, and participated well in design. 2.7+

Kinish has all elements finished but is pretty bare minimum. Fibonacci could use some work in detailing. JS is fairly basic. 2.7

Jay also has all elements. Once again fairly bare minimum in JS though. 2.7

**Comment by horizon-ab** [comment]
Grade: 2.7+

Project - Stats Calculator for AP Stats
- Wireframe with types of data, college board topics, and account creation
- Sample Calculator created
Fibonacci
- Collaboration: everybody explained some part of it
- Dynamic method
Javascript
- Mean Calculator

**Comment by RohanG326** [comment]
Rohan Gaikwad
- Wireframes and idea for stats calculator is solid
- concerned with how far the project could go in terms of features
- fibonacci was well done and detailed in explanation
- js was well done

**Comment by supermengman** [comment]
good website prototype for the stats calculator, work done for outlining data inputs

Kinish + Rohan using abstract as well as timing, good explanations

Jay using arrays for the for loops

Rohan/Gabe using JS for a mean calculator

Overall extra work for all, 2.7+

**Comment by nicm2** [comment]
Wireframes and plan for PBL and design in the future is good and descriptive. Use of Scrum Board to organize tasks. Simple structure of website shows idea and progress towards goal. Explanation of Fibonacci and use of abstract class and extends shows group understanding. Caching is a creative feature. JavaScript project shows use of HTML and JavaScript and allows connects to PBL project. 

Overall: 2.7+

**Comment by jm1021** [comment]
Gab, Jay, Kin - Shared scrum board.  Stats calclulator and members in class.  Had a Stats Calculator.  With mock graphs.

Rohan - Fibo talked to code.  Added a timer. 
Jay - Extended but did not have constructors.  Discussed For algorithm.  

Timing is in extended vs in original class.  Could be wrapped around the init() call.

Did JavaScript adapted to build a calculator.  

2.7

**Comment by rjawesome** [comment]
Complete
