### ISSUE TITLE
Design/ evidence of interest - Team

### ISSUE THREAD

**Issue by Gabrielboudreau** [Gabrielboudreau/CSATeam#6]
- [ ] Basic Design, furthered
- [ ] Runtime on Group site
- [ ] Development of wireframe
- [ ] Basic HTML and CSS (Front Page?)

**Comment by rjawesome** [comment]
Rohan/Kinish:
[Blog](https://kinerboi.github.io/myFirstRepopart2/markdown/2022/10/04/Week-7.html)
[Images](https://spring.rohanj.dev/imageconvert)
[RapidAPI](https://spring.rohanj.dev/currencyconvert)

**Comment by Gabrielboudreau** [comment]
Rohan/Kinish Grading 2.7+, 

Json implementation for api with currency converter, data parsing. Images was implemented into springboot.

**Comment by rjawesome** [comment]
I would give Gabe/Jay a 2.7 because they did a sports API and completed all the images

**Comment by jm1021** [comment]
AP Stats project - Shared Design before.  I still need more confidence on project.

K&R Currency Class API, ASCII, dud frontend and backend ... did all the spring stuff 2.7
J&G Still working on parsing data.  Blue, Green, Grey, Red.     2.6  not strong in API work.

**Comment by rjawesome** [comment]
Graded
